replicaCount: 1

image:
  repository: neoGenesis/core-server
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

postgres:
  enabled: true
  image: "postgres:15"
  storage:
    size: 10Gi
  host: postgres
  port: 5432
  database: neogenesis
  user: neogenesis
  password: neogenesis

admin:
  enabled: true
  user: admin
  password: admin-password

resources: {}

nodeSelector: {}
tolerations: []
affinity: {}
