apiVersion: v1
kind: Service
metadata:
  name: neogenesis-core-server
spec:
  type: {{ .Values.service.type }}
  selector:
    app: neogenesis-core-server
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
