apiVersion: v1
kind: Service
metadata:
  name: neogenesis-core-server
  labels:
    app: neogenesis-core-server
spec:
  type: {{ .Values.service.type }}
  selector:
    app: neogenesis-core-server
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
    - name: grpc
      port: {{ .Values.service.grpcPort }}
      targetPort: grpc
